### PR TITLE
added text on reduced-complexity modes, and update author list

### LINKED ISSUE #8: add descriptions of all reduced complexity configurations to the docs

### PR DESCRIPTION
**Pull request by ckoven**
fixes #8.

### CODE REVIEW

**Comment by ckoven** [comment]
@rosiealice could you take a quick look at this and see if I missed or misstated anything important?

**Comment by ckoven** [comment]
Also, in terms of integration testing, I compiled (sphinxed?) this on my computer and confirm that everything looks as intended.

**Comment by glemieux** [comment]
Thanks Charlie, this looks great.  For future reference, you can also check out the PR test build by clicking on the "Show alll checks".  This exposes the test and allows you to click on "Details" to see the test compilation:
image

**Review by glemieux — APPROVED** [review]

**Comment by rgknox** [comment]
Looks like it generates and compiles ok: https://fates-users-guide--34.org.readthedocs.build/projects/tech-doc/en/34/fates_tech_note.html#fates-reduced-complexity-configurations

**Comment by glemieux** [comment]
We decided to move forward to just pull this.  We discussed having a meeting to review the tech doc in general.  Please feel to review the relevant section @rosiealice and create a new PR if needed.

**Pull request merged**
